FROM python:3.12.2-alpine
LABEL authors="v.lazarev"
RUN pip3 install --upgrade pip

WORKDIR /opt/app_srv

ADD req.txt req.txt
RUN pip3 install --no-cache-dir -r req.txt --break-system-packages

COPY config.py config.py
COPY database.py database.py
COPY exceptions.py exceptions.py
COPY main.py main.py
COPY models.py models.py
COPY req.txt req.txt
COPY test_api.py test_api.py
COPY async_logging.py async_logging.py

ENTRYPOINT ["python3", "main.py"]

EXPOSE 8000
